# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PE3DDownloader
                                 A QGIS plugin
 Plugin para baixar dados do portal Pernambuco Tridimensional diretamente no QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-10
        copyright            : (C) 2025 by weraclitof
        email                : weverton.heraclito@ufpe.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PE3DDownloader class from file PE3DDownloader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pe3d_core import PE3DDownloader
    return PE3DDownloader(iface)
